/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRoomsRouteImport } from './routes/admin.rooms'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminPoliciesRouteImport } from './routes/admin.policies'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminMealsRouteImport } from './routes/admin.meals'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminAmenitiesRouteImport } from './routes/admin.amenities'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPoliciesRoute = AdminPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMealsRoute = AdminMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAmenitiesRoute = AdminAmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/amenities': typeof AdminAmenitiesRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/meals': typeof AdminMealsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/amenities': typeof AdminAmenitiesRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/meals': typeof AdminMealsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/amenities': typeof AdminAmenitiesRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/meals': typeof AdminMealsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/amenities'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/meals'
    | '/admin/payments'
    | '/admin/policies'
    | '/admin/pricing'
    | '/admin/rooms'
    | '/admin/settings'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/amenities'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/meals'
    | '/admin/payments'
    | '/admin/policies'
    | '/admin/pricing'
    | '/admin/rooms'
    | '/admin/settings'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/amenities'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/meals'
    | '/admin/payments'
    | '/admin/policies'
    | '/admin/pricing'
    | '/admin/rooms'
    | '/admin/settings'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/policies': {
      id: '/admin/policies'
      path: '/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AdminPoliciesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/meals': {
      id: '/admin/meals'
      path: '/meals'
      fullPath: '/admin/meals'
      preLoaderRoute: typeof AdminMealsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/amenities': {
      id: '/admin/amenities'
      path: '/amenities'
      fullPath: '/admin/amenities'
      preLoaderRoute: typeof AdminAmenitiesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAmenitiesRoute: typeof AdminAmenitiesRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMealsRoute: typeof AdminMealsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPoliciesRoute: typeof AdminPoliciesRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAmenitiesRoute: AdminAmenitiesRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMealsRoute: AdminMealsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPoliciesRoute: AdminPoliciesRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
